version: 2

updates:
  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: weekly
      day: monday
      time: '10:00'
      timezone: Europe/Moscow
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci
      include: scope
    schedule:
      interval: weekly
      day: monday
      time: '10:00'
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
